#!/bin/sh
#
# @name Gazebo DJI Matrice 4E
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=m4e}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# Asymmetric M4E arm geometry measured from mesh (Blender), ~440 mm diagonal
param set-default CA_ROTOR0_PX  0.18056
param set-default CA_ROTOR0_PY 0.11551
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.15826
param set-default CA_ROTOR1_PY  -0.165
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX  0.15826
param set-default CA_ROTOR2_PY  -0.165
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.18056
param set-default CA_ROTOR3_PY 0.11551
param set-default CA_ROTOR3_KM -0.05

# Gazebo ESC channel mapping
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MIN3 0
param set-default SIM_GZ_EC_MIN4 0
param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

# DJI performance envelope
param set-default MPC_THR_HOVER 0.28
param set-default NAV_DLL_ACT 2
param set-default MPC_XY_VEL_MAX 21.0
param set-default MPC_XY_CRUISE 13.0
param set-default MPC_ACC_HOR 5.0
param set-default MPC_Z_VEL_MAX_UP 10.0
param set-default MPC_Z_VEL_MAX_DN 8.0
param set-default MPC_MAN_TILT_MAX 35.0

# Disable battery health check in SITL simulation
param set-default CBRK_BAT_FAIL 283158

